### ISSUE TITLE
subsecond info is not sent to NewRelic API

### ISSUE THREAD

**Issue by danielsig727** [newrelic/newrelic-fluentd-output#19]
Hi, 

I found that all the log entries sent to NewRelic Logs lost their subsecond info in the timestamp. So all the timestamps in the Logs dashboard only have integer second numbers.

After a bit of digging, I found out that the `nsec` field in the timestamp is not utilized when forming the request data to NR API. I have a commit that works for me https://github.com/danielsig727/newrelic-fluentd-output/commit/48602db2c6b9472159418e9a683a1281eef61768 . If you're fine with it, I can create a PR for it. Thanks

**Comment by bmcfeely** [comment]
Thanks, @danielsig727, you rock. Please do create a PR, or we can create one as well, whatever's easiest. 

Breadcrumb for myself: here's where the timestamp changed from int to object: https://github.com/fluent/fluentd/pull/653/files

**Comment by danielsig727** [comment]
PR #22 sent. thanks!
