### ISSUE TITLE
Logs are not visible in UI

### ISSUE THREAD

**Issue by zebkailash** [newrelic/newrelic-fluentd-output#28]
I can see the response with 202 in plugin but logs don't appear in UI. Same works if i call the http endpoint and send the same logs.

**Comment by bmcfeely** [comment]
Sorry for the delay -- @zebkailash do you still have this problem? If so, please reach out to [New Relic Support](https://support.newrelic.com/) and we can get you up and running! Thank you.

**Comment by zebkailash** [comment]
Thank you @bmcfeely for the early response due to time constraints I had to create a workaround by using the fluentd HTTP plugin.
