### ISSUE TITLE
do not chunk on timestamp

### ISSUE THREAD

**Issue by rittneje** [newrelic/newrelic-fluentd-output#39]
Currently by default this plugin will chunk the logs based on timestamp. https://github.com/newrelic/newrelic-fluentd-output/blob/be9232133b18023f000d7097411934832fe5020c/lib/fluent/plugin/out_newrelic.rb#L40 This means it will spam the logging API based upon the granularity of your timestamps. For example, if your timestamps have the granularity of seconds, it will send logs every second. This is apparently too much for the server to handle at scale, so it basically drops everything.

Instead, this plugin should default to chunking over a larger time window. Or at least this should be mentioned in the README. https://docs.fluentd.org/configuration/buffer-section#time

**Comment by danybmx** [comment]
Thanks @rittneje for reporting this, we've changed the default buffer type to use chunks of 5s instead use the timestamp attribute granularity.

Also we're updating the NR public documentation to add this details and an example of how to change the default configuration. https://github.com/newrelic/docs-website/pull/3343/files
